# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Kappas <- function(y) {
    .Call(`_MBRM_Kappas`, y)
}

dBer_LGG <- function(theta, X, y, return_log = TRUE) {
    .Call(`_MBRM_dBer_LGG`, theta, X, y, return_log)
}

lvero <- function(theta, X_list, y_list) {
    .Call(`_MBRM_lvero`, theta, X_list, y_list)
}

